GET   http://localhost:3000/api/posts HTTP/1.1

###

GET   http://localhost:3000/posts/1 HTTP/1.1

###

POST  http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
  "title": "rest client",
  "content": "it is easy",
  "tags": [
    "json-server",
    "rest",
    "client"
  ],
  "imageUrl": "https://thumbs.dreamstime.com/b/sunrise-over-modern-skyline-dubai-uae-urban-construction-109241413.jpg",
  "authorId": 1
}

###

PUT  http://localhost:3000/posts/3 HTTP/1.1
content-type: application/json

{
  "title": "rest client advanced",
  "content": "it isnt easy!!",
  "tags": [
    "http",
    "rest",
    "client"
  ],
  "imageUrl": "https://thumbs.dreamstime.com/b/sunrise-over-modern-skyline-dubai-uae-urban-construction-109241413.jpg",
  "authorId": 1
}

###

DELETE http://localhost:3000/posts/3 HTTP/1.1